### ISSUE TITLE
Big files upload

### ISSUE THREAD

**Issue by rafapaulin** [kfirba/Directo#2]
Hello!

is there any config that could be set to make files > 5gb upload correctly to s3? it seems it ust be multiparted uploaded.

Thanks

**Comment by kfirba** [comment]
@rafapaulin As far as I know, in order to do so, you need to split the file and upload it in multipart. 
There seems to be a package that handles that but bear in mind that you will need to implement the server side signing: https://github.com/TTLabs/EvaporateJS

Maybe you can use Directo to generate signatures on your server in order for it to work with EvaporateJS.
